services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pinkkstore_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '127.0.0.1:5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '127.0.0.1:5672:5672'