server:
  port: 8090

spring:
  application:
    name: store-api


  datasource:
    username: myuser
    password: secret
    url: "jdbc:postgresql://127.0.0.1:5432/pinkkstore_db"

  sql:
    init:
      mode: always
#       When locally developing both Store and CRM, you can use shared schema and data.
#      schema-locations: file:api-db/schema.sql
#      data-locations: file:api-db/data.sql


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: health


logging:
  level:
    org.springframework.security: trace
#    org.springframework.data: trace
#    org.springframework.web: trace

