spring:
  config:
    import: aws-secretsmanager:pinkkstore_db-secrets;

  datasource:
    username: ${username}
    password: ${password}
    url: jdbc:postgresql://${host}:${port}/${dbname}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.pinkkstore.com/oauth2/jwks