server:
  port: 9000

spring:
  application:
    name: store-auth-server

  datasource:
    username: myuser
    password: secret
    url: "jdbc:postgresql://127.0.0.1:5432/pinkkstore_db"

  sql:
    init:
      mode: always

  security:
    oauth2:
      authorizationserver:
        client:
          store-client:
            registration:
              client-id: "store-bff-client"
              client-secret: "$2a$10$urICP3Nt8Ni8riaVQCYi0OAxkYvqL7TXBo3u/7z8IaTNb3tivS2W2"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8070/login/oauth2/code/store-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8070/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "cart.read"
                - "cart.write"
                - "order.read"
                - "order.write"
            require-authorization-consent: false

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.security: trace