# test if this is really needed:
server:
  forward-headers-strategy: native

spring:
  config:
    import:
      - aws-secretsmanager:client-secrets

  security:
    oauth2:
      client:
        registration:
          store-client:
            provider: spring
            client-id: store-bff-client
            client-secret: ${bff-client}
            authorization-grant-type: authorization_code
            redirect-uri: "https://pinkkstore.com/login/oauth2/code/{registrationId}"
            scope: openid,profile,cart.read,cart.write,order.read,order.write
            client-name: store-client
        provider:
          spring:
            issuer-uri: https://auth.pinkkstore.com

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: userinfo
              uri: https://auth.pinkkstore.com
              predicates:
                - Path=/userinfo
              filters:
                - TokenRelay=
            - id: resource-server
              uri: https://api.pinkkstore.com
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - StripPrefix=1

app:
  base-uri: https://pinkkstore.com
  authentication-entry-point: https://pinkkstore.com/oauth2/authorization/store-client
