server:
  port: 8080

spring:
  application:
    name: store-bff

  security:
    oauth2:
      client:
        registration:
          store-client-oidc:
            provider: spring
            client-id: store-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8070/login/oauth2/code/{registrationId}"
            scope: openid,profile
            client-name: store-client-oidc
          store-client-authorization-code:
            provider: spring
            client-id: store-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8070/authorized"
            scope: openid,profile
            client-name: store-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: userinfo
              uri: http://localhost:9000
              predicates:
                - Path=/userinfo
              filters:
                - TokenRelay=
            - id: resource-server
              uri: http://localhost:8090
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - StripPrefix=1

app:
  base-uri: http://127.0.0.1:8070
  authentication-entry-point: http://127.0.0.1:8070/oauth2/authorization/store-client-oidc
#  authentication-entry-point: /oauth2/authorization/store-client-oidc

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.security: trace