server:
  port: 8070
  forward-headers-strategy: native

spring:
  application:
    name: store-reverse-proxy

  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: oauth2-login
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/oauth2/authorization/**
            - id: oauth2-callback
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/login/**
            - id: logout
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/logged-out
            - id: bff-api
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/api/**
            - id: bff
              uri: http://127.0.0.1:8080
              predicates:
                - Path=/bff/**
              filters:
                - StripPrefix=1
            - id: auth
              uri: http://localhost:9000
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: frontend
              uri: http://127.0.0.1:3000
              predicates:
                - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: health