spring:
  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: oauth2-login
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/oauth2/authorization/**
            - id: oauth2-callback
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/login/**
            - id: oauth2-authorized
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/authorized
            - id: logout
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/logged-out
            - id: bff-api
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/api/**
            - id: bff
              uri: https://bff.pinkkstore.com
              predicates:
                - Path=/bff/**
              filters:
                - StripPrefix=1
            - id: auth
              uri: https://auth.pinkkstore.com
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: frontend
              uri: https://frontend.pinkkstore.com
              predicates:
                - Path=/**